In [1]:
import numpy as np
import matplotlib.pylab as plt
import pandas as pd
import plotly.graph_objects as go

1. Para simular un conjunto de características $x_1$ , $x_2$,..., $x_n$ trabajaremos en la primera parte con dos características de datos aleatorios que presentan un plano y mostraremos que los párametros optimizados se corresponden con el valor esperado.

- Definir la ecuación  $y = 2.1*x_1 - 3.1*x_2$, y generar números aleatorios que pertenecen al plano.

- Realizar un diagrama 3D de los puntos generados aleatoriamente.


Nuestro objetivo será encontrar los valores $\theta_0 = 0, \theta_1=2.1, \theta_1=3.1$ que mejor ajustar el plano, empleando cálculos vectorizados.

In [6]:
N=100
x1= 2*np.random.random(N)-1
x2= 2*np.random.random(N)-1
X_1,X_2 =np.meshgrid(x1, x2)
y_label = 0.2 * x1 - 0.5 * x2
Y = 2.1*X_1 - 3.1*X_2

fig = go.Figure(go.Surface(x=X_1, y=X_2, z=Y))
fig.add_trace(go.Scatter3d(x=x1, y=x2, z=y_label, mode='markers', marker=dict(size=4, color='white')))
fig.show()

In [12]:
df = pd.DataFrame({"x1":x1, "x2":x2, "y":y_label})
df["ones"]=1
df

x1        x2         y  ones
0   0.493427  0.582563 -0.192596     1
1   0.206701 -0.882339  0.482510     1
2   0.796591  0.485550 -0.083457     1
3  -0.809389  0.196367 -0.260062     1
4  -0.019064  0.541875 -0.274750     1
..       ...       ...       ...   ...
95 -0.832167  0.531106 -0.431986     1
96  0.925452  0.672971 -0.151395     1
97  0.234744  0.991837 -0.448970     1
98 -0.340591 -0.511481  0.187622     1
99 -0.716727 -0.285280 -0.000706     1

[100 rows x 4 columns]

2. Inicializar conjunto de parámetros $\Theta$ de manera aleatoria.

In [25]:
theta = np.random.random(3).reshape(3, 1)
theta #nuestro vector de thetas aletorios

array([[0.23509736],
       [0.58533871],
       [0.85605651]])

3. Construir la matrix X con dimensiones $(n+1, m)$, m es el numero de datos de entrenamiento y (n) el número de caracteristicas.

In [14]:
X = df[["ones", "x1", "x2"]].values.T
X

array([[ 1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1. 

4. Calcular la función de coste(revise cuidosamente las dimensiones de cada matriz):

  - $h = \Theta^{T} X $
  - $\Lambda= (h -Y) $
  - $\Lambda*= (h -Y)^2 $
  - $\Lambda= [\Lambda_1,\Lambda_2, ...,\Lambda_m]$
  - $J = \frac{1}{2m} \sum_{i}^m \Lambda_i $

In [20]:
def model(theta, X):
  return theta.T@X

def costo(h, Y):
  J= (h-Y)**2
  return J.mean()

costo1 = costo(model(theta,X), Y)
costo1

0.6550103198526923

5. Aplicar el gradiente descendente:
  - Encontrar el gradiente.
    \begin{equation}
\nabla J = \Lambda^T X
\end{equation}
  
  - Actualizar los nuevos parametros:
    \begin{equation}
\Theta=\Theta-\alpha \nabla J
\end{equation}




In [18]:
def gradiente_descendente(theta, h, Y, k):
  grad = np.dot((h-Y), X.T).T
  theta = theta - k*grad
  return theta

In [26]:
k = 0.01
Niter = 100
J = np.zeros(Niter)

for i in range(0, Niter):
  h = model(theta, X)
  J[i] = costo(h, Y)
  theta = gradiente_descendente(theta, h, Y, k)

6. Iterar para encontrar los valores $\Theta$ que se ajustan el plano.


In [27]:
theta #Donde vemos que coinciden con los valores esperados.

array([[ 9.07274262e-18],
       [ 2.00000000e-01],
       [-5.00000000e-01]])