In [4]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
from scipy.interpolate import griddata


In [5]:
""""
Para simular un conjunto de características $x_1$ , $x_2$,..., $x_n$ 
trabajaremos en la primera parte con dos características de datos aleatorios que presentan 
un plano y mostraremos que los párametros optimizados se corresponden con el valor esperado.

- Definir la ecuación  $y = 2.1*x_1 - 3.1*x_2$, y generar números aleatorios que pertenecen al plano. 

- Realizar un diagrama 3D de los puntos generados aleatoriamente. 
"""

x1 = np.random.rand(5)
x2 = np.random.rand(5)
y = 2.1*x1 - 3.1*x2
X1, X2 = np.meshgrid(x1, x2)

Y = 2.1*X1 - 3.1*X2

df = pd.DataFrame({'X1': x1, 'X2': x2, 'Y': y})

In [6]:
# Create scatter plot
fig = px.scatter_3d(x=X1.flatten(), y=X2.flatten(), z=Y.flatten())
fig.update_traces(marker=dict(size=1))

# Create a meshgrid for the surface plot
X1_grid, X2_grid = np.meshgrid(np.linspace(X1.min(), X1.max(), 100), np.linspace(X2.min(), X2.max(), 100))

# Interpolate Y values for the meshgrid
Y_grid = griddata((X1.flatten(), X2.flatten()), Y.flatten(), (X1_grid, X2_grid), method='linear')

# Add surface plot for shading
fig.add_trace(go.Surface(x=X1_grid, y=X2_grid, z=Y_grid, opacity=0.5, colorscale='Viridis'))

fig.show()

In [17]:
""""
2. Inicializar conjunto de parámetros theta de manera aleatoria.

"""

Thetas = np.random.rand(3)
Thetas

array([0.48080007, 0.29589645, 0.11994372])

In [18]:
"""
3. Construir la matrix X con dimensiones $(n+1, m)$, m es el numero de datos de entrenamiento y (n) el número de caracteristicas.

"""

X = np.vstack((np.ones(x1.size), x1, x2))
X

array([[1.        , 1.        , 1.        , 1.        , 1.        ],
       [0.17366959, 0.57703099, 0.95693549, 0.16279829, 0.62127617],
       [0.83844677, 0.75995279, 0.0019233 , 0.90180398, 0.52836358]])

In [19]:
H = Thetas @ X
H

array([0.63275471, 0.74269306, 0.76418457, 0.63713723, 0.72800738])

In [20]:
""""
4. Calcular la función de coste(revise cuidosamente las dimensiones de cada matriz)

"""
J = lambda H, y: (1/(2*y.shape[0])) * np.sum((H - y)**2)
J_value = J(H, y)

f'El valor de la función de coste es: {J_value:.2f}'

'El valor de la función de coste es: 2.40'

In [21]:
""""
5. Encontrar el gradiente descendiente de la función de coste.

"""
T_update = lambda Thetas, X, Lambda, alpha: Thetas - alpha*Lambda@X.T


In [22]:
Lambda = (H-y)**2
Thetas_ = T_update(Thetas, X, Lambda, 0.01)
H_new = Thetas_ @ X
J_new = J(H_new, y)
f'El valor de la función de coste al aplicar grad descendente es: {J_new:.2f}'



'El valor de la función de coste es: 1.82'